# Copty the example main setup file
# This will have to be renamed to setup.properties
cp resources/example_setup.properties ~/.config/solarsystemsim/example_setup.properties

# Copy example system setups, including the autogenerated one
cp resources/example_system.properties ~/.config/solarsystemsim/example_system.properties
cp resources/solar_system.properties ~/.config/solarsystemsim/solar_system.properties
cp resources/random_system.properties ~/.config/solarsystemsim/out/random_system.properties
