:: Copy the example main setup file
:: This will have to be renamed to setup.properties
copy resources\example_setup.properties %userprofile%\.config\solarsystemsim\example_setup.properties

:: Copy example system setups, including the autogenerated one
copy resources\example_system.properties %userprofile%\.config\solarsystemsim\example_system.properties
copy resources\solar_system.properties %userprofile%\.config\solarsystemsim\solar_system.properties
copy resources\out\random_system.properties %userprofile%\.config\solarsystemsim\random_system.properties
